[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
yieldmind = "Ch4GZssLa7sXnS1cWTwatM2GtJu3SbQ6bSTgkz4EsuJ6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
